### ISSUE TITLE
[Question] Loguru handler with Opentelemetry: Invalid type dict for attribute 'extra' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types

### ISSUE THREAD

**Issue by lnk2005** [Delgan/loguru#1063]
When using `opentelemetry-collter` to collect logs, `loguru` will throw a warning like this: `Invalid type dict for attribute 'extra' value. Expected one of ['bool', 'str', 'bytes', 'int' , 'float'] or a sequence of those types`

## my code:
```python
import logging

from loguru import logger
from opentelemetry import trace
from opentelemetry._logs import set_logger_provider
from opentelemetry.exporter.otlp.proto.grpc._log_exporter import (
    OTLPLogExporter,
)
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (
    BatchSpanProcessor,
    ConsoleSpanExporter,
)

if __name__ == '__main__':
    trace.set_tracer_provider(TracerProvider())
    trace.get_tracer_provider().add_span_processor(
        BatchSpanProcessor(ConsoleSpanExporter())
    )

    logger_provider = LoggerProvider(
        resource=Resource.create(
            {
                "service.name": "shoppingcart",
                "service.instance.id": "instance-12",
            }
        ),
    )
    set_logger_provider(logger_provider)

    exporter = OTLPLogExporter(insecure=True)
    logger_provider.add_log_record_processor(BatchLogRecordProcessor(exporter))
    handler = LoggingHandler(level=logging.NOTSET, logger_provider=logger_provider)

    # remove console
    logger.remove()
    logger.add(handler, serialize=True)
    logger.info('logs without trace')


    # Trace context correlation
    tracer = trace.get_tracer(__name__)
    with tracer.start_as_current_span("foo"):
        # Do something
        # logger2.error("Hyderabad, we have a major problem.")
        logger.error("Hyderabad, we have a major problem.")

    logger_provider.shutdown()
```

## console output:
![截屏2024-01-05 17 33 40](https://github.com/Delgan/loguru/assets/43910502/13f7a83c-ce3b-4d2f-9e88-d7e14fe3156b)

## env:
```toml
# pyproject.toml

[tool.poetry.dependencies]
python = "^3.12"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"
opentelemetry-exporter-jaeger = "^1.21.0"
pymongo = "^4.6.1"
opentelemetry-instrumentation = "^0.43b0"
opentelemetry-distro = "^0.43b0"
opentelemetry-exporter-otlp-proto-grpc = "^1.22.0"
opentelemetry-instrumentation-pymongo = "^0.43b0"
opentelemetry-exporter-otlp = "^1.22.0"
loguru = "^0.7.2"
opentelemetry-instrumentation-logging = "^0.43b0"
```

system: macOS 14.2.1 (23C71)
