### ISSUE TITLE
Feature request: get config from pyproject.toml

### ISSUE THREAD

**Issue by lewiuberg** [Delgan/loguru#839]
Hi!

I want to use `pyproject.toml` to configure `loguru`, but it does not seem to be implemented.

I just tested this snippet in `loguru/loguru
/__init__.py`:

```python
import toml

def get_loguru_config():
    """Read pyproject.toml."""
    try:
        with open("pyproject.toml") as f:
            pyproject = toml.load(f)
        return pyproject["tool"]["loguru"]
    except FileNotFoundError as e:
        logger.error(f"FileNotFoundError: {e}")
    except KeyError as e:
        logger.error(f"KeyError: {e}")
```

then I added this snippet to `pyproject.toml`:

```toml
[tool.loguru]
[[tool.loguru.handlers]]
sink = "logs/loguru.log"
rotation = "1 minute"
compression = "zip"
serialize = false
retention = "10 minutes"
```

Then I added this to the file I am using the logger in, and it worked:

```python
from loguru import logger, get_loguru_config

config = get_loguru_config()

logger.configure(**config)
```

With some more work and having things in the correct places, this should be possible automatically.

Are there any plans for such a feature?
